PROJECT_NAME = testProject
PROJECT_DIR = .
FRAMEWORK_DIR = ../..
CSOURCES = main.c
USE_CLASSES=yes
LIBRARIES = usb-cdc mpu6050 hmc5883 ms5611
PLATFORM = stm32f103ze

include $(FRAMEWORK_DIR)/platform/rules.mk