#include <stm32.h>

const STM32PeriphInfo stm32PeriphTable[] = {
#ifdef STM32F1
	{GPIOA_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPAEN},
	{GPIOB_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPBEN},
	{GPIOC_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPCEN},
	{GPIOD_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPDEN},
	#ifdef GPIOE_BASE
		{GPIOE_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPEEN},
	#endif
	#ifdef GPIOF_BASE
		{GPIOF_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPFEN},
	#endif
	#ifdef GPIOG_BASE
		{GPIOG_BASE, &RCC->APB2ENR, RCC_APB2ENR_IOPGEN},
	#endif
#else
	{GPIOA_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN},
	{GPIOB_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN},
	{GPIOC_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN},
	{GPIOD_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN},
	#ifdef GPIOE_BASE
		{GPIOE_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOEEN},
	#endif
	#ifdef GPIOF_BASE
		{GPIOF_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOFEN},
	#endif
	#ifdef GPIOG_BASE
		{GPIOG_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOGEN},
	#endif
	#ifdef GPIOH_BASE
		{GPIOH_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOHEN},
	#endif
	#ifdef GPIOI_BASE
		{GPIOI_BASE, &RCC->AHB1ENR, RCC_AHB1ENR_GPIOIEN},
	#endif
#endif
	{USART1_BASE, &RCC->APB2ENR, RCC_APB2ENR_USART1EN},
	{USART2_BASE, &RCC->APB1ENR, RCC_APB1ENR_USART2EN},
	{USART3_BASE, &RCC->APB1ENR, RCC_APB1ENR_USART3EN},
	{UART4_BASE, &RCC->APB1ENR, RCC_APB1ENR_UART4EN},
	{UART5_BASE, &RCC->APB1ENR, RCC_APB1ENR_UART5EN},
#ifdef USART6
	{USART6_BASE, &RCC->APB2ENR, RCC_APB2ENR_USART6EN},
#endif
	{I2C1_BASE, &RCC->APB1ENR, RCC_APB1ENR_I2C1EN},
	{I2C2_BASE, &RCC->APB1ENR, RCC_APB1ENR_I2C2EN},
#ifdef I2C3
	{I2C3_BASE, &RCC->APB1ENR, RCC_APB1ENR_I2C3EN},
#endif
#ifdef AFIO_BASE
	{AFIO_BASE, &RCC->APB2ENR, RCC_APB2ENR_AFIOEN},
#endif
#ifdef SYSCFG_BASE
	{SYSCFG_BASE, &RCC->APB2ENR, RCC_APB2ENR_SYSCFGEN},
#endif
#ifdef USB_BASE
	{USB_BASE, &RCC->APB1ENR, RCC_APB1ENR_USBEN},
#endif
#ifdef OTG_FS_GLOBAL_BASE
	{OTG_FS_GLOBAL_BASE, &RCC->AHB2ENR, RCC_AHB2ENR_OTGFSEN},
#endif
	{TIM1_BASE, &RCC->APB2ENR, RCC_APB2ENR_TIM1EN},
	{TIM8_BASE, &RCC->APB2ENR, RCC_APB2ENR_TIM8EN},
	{TIM9_BASE, &RCC->APB2ENR, RCC_APB2ENR_TIM9EN},
	{TIM10_BASE, &RCC->APB2ENR, RCC_APB2ENR_TIM10EN},
	{TIM11_BASE, &RCC->APB2ENR, RCC_APB2ENR_TIM11EN},
	{TIM2_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM2EN},
	{TIM3_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM3EN},
	{TIM4_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM4EN},
	{TIM5_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM5EN},
	{TIM6_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM6EN},
	{TIM7_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM7EN},
	{TIM12_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM12EN},
	{TIM13_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM13EN},
	{TIM14_BASE, &RCC->APB1ENR, RCC_APB1ENR_TIM14EN},
	{ADC1_BASE, &RCC->APB2ENR, RCC_APB2ENR_ADC1EN},
#ifdef ADC2_BASE
	{ADC2_BASE, &RCC->APB2ENR, RCC_APB2ENR_ADC2EN},
#endif
#ifdef ADC3_BASE
	{ADC3_BASE, &RCC->APB2ENR, RCC_APB2ENR_ADC3EN},
#endif
	{}
};

const STM32PeriphInfo *stm32SearchPeriph(volatile void *periph) {
	const STM32PeriphInfo *info = stm32PeriphTable;
	while (info->base && (info->base != (uint32_t)periph)) {
		info++;
	}
	return info->base ? info : 0;
}
